# Generated by Django 5.0.1 on 2024-02-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptrion',
            new_name='description',
        ),
    ]
